[workspace]
members = ["parconv"]

[package]
name = "jpcrs"
version = "0.1.0"
edition = "2021"
description = "Transform coordinate systems used in Japan"
keywords = ["geospatial", "jgd"]

[dependencies]
