[package]
name = "jpcrs"
version = "0.1.0"
edition = "2021"
description = "Transform coordinate reference systems in Japan"
keywords = ["geospatial", "jgd"]

[workspace]
members = ["par"]

[features]
# default = ["geo-types"]       # tmp
geo-types = ["dep:geo-types"]

[dependencies]
geo-types = { version = "0.7.13", optional = true }

[dev-dependencies]
geo-types = "0.7.13"
