name: Rust

on:
  push:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        default: none
        options:
          - none
          - patch
          - minor

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make

  publish:
    if: "${{ inputs.bump != 'none' }}"
    # needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo install cargo-edit
        cargo set-version --bump ${{ inputs.bump }}
        git commit --all -m "v${{ inputs.bump }}"
        git tag "v${{ inputs.bump }}"
